server:
  port: 8082

spring:
  application:
    name: ucenter
#  cloud:
#    config:
#      uri: http://localhost:8888
  jackson:
      default-property-inclusion: non_null
#  zipkin:
#    base-url: http://localhost:11008

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.101:8761/eureka/

endpoints:
  shutdown:
    enabled: true
    sensitive: false
#    server:
#      address: localhost

